### ISSUE TITLE
可能添加按up间隔次数排序吗

### ISSUE THREAD

**Issue by LawrenceZhang** [KeyPJ/genshin-gacha-banners#1]
网页做的很棒，非常有用。但是有时候想看看距离自己想要的角色已经多久没up了，还有多少角色的up间隔次数排在我想要的角色前面。
举例：
刻晴（间隔22个池子未up） 排第一
可莉（间隔16个池子未up） 排第二
万叶（间隔15个池子未up） 排第三
以此类推

**Comment by KeyPJ** [comment]
第一行是可以点击的,点击"实装时间顺序"即可切换至"间隔时间倒序"
